linters:
  enable:
    - gofmt          # フォーマットチェック
    - goimports      # importチェック
    - govet          # 疑わしい構造を検出
    - errcheck       # エラーハンドリング漏れ検出
    - staticcheck    # 高度な静的解析
    - gosimple       # 簡略化可能なコードを指摘
    - unused         # 未使用のコード検出
    - ineffassign    # 無駄な代入検出
    - typecheck      # 型チェック
    - misspell       # スペルミス検出
    - goconst        # 定数化可能な文字列検出
    - gocyclo        # 循環的複雑度チェック

linters-settings:
  gocyclo:
    min-complexity: 15  # 関数の複雑度上限
  goconst:
    min-len: 3
    min-occurrences: 3
  errcheck:
    check-blank: true

issues:
  exclude-dirs:
    - bin
    - vendor
  exclude-use-default: false
  max-same-issues: 0
  exclude-rules:
    # Protobuf generated code
    - path: '\.pb\.go$'
      linters:
        - all

run:
  timeout: 5m
