// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/worker/v1/worker.proto

package workerv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JobStatus はジョブのステータス
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_QUEUED      JobStatus = 1 // キューに入った
	JobStatus_JOB_STATUS_PROCESSING  JobStatus = 2 // エンコード中
	JobStatus_JOB_STATUS_UPLOADING   JobStatus = 3 // アップロード中
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 4 // 完了
	JobStatus_JOB_STATUS_FAILED      JobStatus = 5 // 失敗
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 6 // キャンセル
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_QUEUED",
		2: "JOB_STATUS_PROCESSING",
		3: "JOB_STATUS_UPLOADING",
		4: "JOB_STATUS_COMPLETED",
		5: "JOB_STATUS_FAILED",
		6: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_QUEUED":      1,
		"JOB_STATUS_PROCESSING":  2,
		"JOB_STATUS_UPLOADING":   3,
		"JOB_STATUS_COMPLETED":   4,
		"JOB_STATUS_FAILED":      5,
		"JOB_STATUS_CANCELLED":   6,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_proto_worker_v1_worker_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

// JobRequest はエンコードジョブのリクエスト
type JobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id は一意のジョブID（Control Planeが生成）
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// input_url はエンコード対象の入力URL
	InputUrl string `protobuf:"bytes,2,opt,name=input_url,json=inputUrl,proto3" json:"input_url,omitempty"`
	// preset はエンコード設定のプリセット名（例: "720p_h264"）
	Preset string `protobuf:"bytes,3,opt,name=preset,proto3" json:"preset,omitempty"`
	// output はアップロード先の設定
	Output *OutputConfig `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	// callback_url はジョブ完了時に呼び出すWebhook URL（オプション）
	CallbackUrl   string `protobuf:"bytes,5,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_proto_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRequest) GetInputUrl() string {
	if x != nil {
		return x.InputUrl
	}
	return ""
}

func (x *JobRequest) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *JobRequest) GetOutput() *OutputConfig {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *JobRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

// OutputConfig はアップロード先の設定
type OutputConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// storage はストレージタイプ（"s3", "ftp", "local" など）
	Storage string `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	// path はアップロード先のパス
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// metadata は任意のメタデータ
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// type は出力タイプ（"single", "hls", "dash"）デフォルトは "single"
	Type          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputConfig) Reset() {
	*x = OutputConfig{}
	mi := &file_proto_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputConfig) ProtoMessage() {}

func (x *OutputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputConfig.ProtoReflect.Descriptor instead.
func (*OutputConfig) Descriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *OutputConfig) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *OutputConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OutputConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OutputConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// JobProgress はジョブの進捗情報
type JobProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id はジョブID
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// status はジョブのステータス
	Status JobStatus `protobuf:"varint,2,opt,name=status,proto3,enum=worker.v1.JobStatus" json:"status,omitempty"`
	// progress は進捗率（0-100）
	Progress float32 `protobuf:"fixed32,3,opt,name=progress,proto3" json:"progress,omitempty"`
	// message は進捗メッセージ
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// timestamp はタイムスタンプ（RFC3339形式）
	Timestamp string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// output_url は完了時のアップロード先URL
	OutputUrl string `protobuf:"bytes,6,opt,name=output_url,json=outputUrl,proto3" json:"output_url,omitempty"`
	// error はエラー発生時のエラーメッセージ
	Error         string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	mi := &file_proto_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *JobProgress) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobProgress) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *JobProgress) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *JobProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobProgress) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *JobProgress) GetOutputUrl() string {
	if x != nil {
		return x.OutputUrl
	}
	return ""
}

func (x *JobProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// StatusRequest は Worker 状態取得のリクエスト
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

// WorkerStatus は Worker の現在の状態
type WorkerStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// current_jobs は現在実行中のジョブ数
	CurrentJobs int32 `protobuf:"varint,1,opt,name=current_jobs,json=currentJobs,proto3" json:"current_jobs,omitempty"`
	// max_concurrent_jobs は最大同時実行数
	MaxConcurrentJobs int32 `protobuf:"varint,2,opt,name=max_concurrent_jobs,json=maxConcurrentJobs,proto3" json:"max_concurrent_jobs,omitempty"`
	// active_job_ids は実行中のジョブID一覧
	ActiveJobIds []string `protobuf:"bytes,3,rep,name=active_job_ids,json=activeJobIds,proto3" json:"active_job_ids,omitempty"`
	// worker_id は Worker の識別子
	WorkerId string `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// version は Worker のバージョン
	Version       string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerStatus) Reset() {
	*x = WorkerStatus{}
	mi := &file_proto_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerStatus) ProtoMessage() {}

func (x *WorkerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerStatus.ProtoReflect.Descriptor instead.
func (*WorkerStatus) Descriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

func (x *WorkerStatus) GetCurrentJobs() int32 {
	if x != nil {
		return x.CurrentJobs
	}
	return 0
}

func (x *WorkerStatus) GetMaxConcurrentJobs() int32 {
	if x != nil {
		return x.MaxConcurrentJobs
	}
	return 0
}

func (x *WorkerStatus) GetActiveJobIds() []string {
	if x != nil {
		return x.ActiveJobIds
	}
	return nil
}

func (x *WorkerStatus) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// CancelRequest はジョブキャンセルのリクエスト
type CancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id はキャンセルするジョブID
	JobId         string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// CancelResponse はジョブキャンセルのレスポンス
type CancelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success はキャンセルが成功したかどうか
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message はレスポンスメッセージ
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_worker_v1_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_worker_v1_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_worker_v1_worker_proto_rawDescGZIP(), []int{6}
}

func (x *CancelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_worker_v1_worker_proto protoreflect.FileDescriptor

const file_proto_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/worker/v1/worker.proto\x12\tworker.v1\"\xac\x01\n" +
	"\n" +
	"JobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tinput_url\x18\x02 \x01(\tR\binputUrl\x12\x16\n" +
	"\x06preset\x18\x03 \x01(\tR\x06preset\x12/\n" +
	"\x06output\x18\x04 \x01(\v2\x17.worker.v1.OutputConfigR\x06output\x12!\n" +
	"\fcallback_url\x18\x05 \x01(\tR\vcallbackUrl\"\xd0\x01\n" +
	"\fOutputConfig\x12\x18\n" +
	"\astorage\x18\x01 \x01(\tR\astorage\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.worker.v1.OutputConfig.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x01\n" +
	"\vJobProgress\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.worker.v1.JobStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x02R\bprogress\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"output_url\x18\x06 \x01(\tR\toutputUrl\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"\x0f\n" +
	"\rStatusRequest\"\xbe\x01\n" +
	"\fWorkerStatus\x12!\n" +
	"\fcurrent_jobs\x18\x01 \x01(\x05R\vcurrentJobs\x12.\n" +
	"\x13max_concurrent_jobs\x18\x02 \x01(\x05R\x11maxConcurrentJobs\x12$\n" +
	"\x0eactive_job_ids\x18\x03 \x03(\tR\factiveJobIds\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"&\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"D\n" +
	"\x0eCancelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xbe\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11JOB_STATUS_QUEUED\x10\x01\x12\x19\n" +
	"\x15JOB_STATUS_PROCESSING\x10\x02\x12\x18\n" +
	"\x14JOB_STATUS_UPLOADING\x10\x03\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x04\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x05\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x062\xcf\x01\n" +
	"\rWorkerService\x12<\n" +
	"\tSubmitJob\x12\x15.worker.v1.JobRequest\x1a\x16.worker.v1.JobProgress0\x01\x12>\n" +
	"\tGetStatus\x12\x18.worker.v1.StatusRequest\x1a\x17.worker.v1.WorkerStatus\x12@\n" +
	"\tCancelJob\x12\x18.worker.v1.CancelRequest\x1a\x19.worker.v1.CancelResponseB6Z4github.com/nzws/flux-encoder/proto/worker/v1;workerv1b\x06proto3"

var (
	file_proto_worker_v1_worker_proto_rawDescOnce sync.Once
	file_proto_worker_v1_worker_proto_rawDescData []byte
)

func file_proto_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_proto_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_proto_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_worker_v1_worker_proto_rawDesc), len(file_proto_worker_v1_worker_proto_rawDesc)))
	})
	return file_proto_worker_v1_worker_proto_rawDescData
}

var file_proto_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_worker_v1_worker_proto_goTypes = []any{
	(JobStatus)(0),         // 0: worker.v1.JobStatus
	(*JobRequest)(nil),     // 1: worker.v1.JobRequest
	(*OutputConfig)(nil),   // 2: worker.v1.OutputConfig
	(*JobProgress)(nil),    // 3: worker.v1.JobProgress
	(*StatusRequest)(nil),  // 4: worker.v1.StatusRequest
	(*WorkerStatus)(nil),   // 5: worker.v1.WorkerStatus
	(*CancelRequest)(nil),  // 6: worker.v1.CancelRequest
	(*CancelResponse)(nil), // 7: worker.v1.CancelResponse
	nil,                    // 8: worker.v1.OutputConfig.MetadataEntry
}
var file_proto_worker_v1_worker_proto_depIdxs = []int32{
	2, // 0: worker.v1.JobRequest.output:type_name -> worker.v1.OutputConfig
	8, // 1: worker.v1.OutputConfig.metadata:type_name -> worker.v1.OutputConfig.MetadataEntry
	0, // 2: worker.v1.JobProgress.status:type_name -> worker.v1.JobStatus
	1, // 3: worker.v1.WorkerService.SubmitJob:input_type -> worker.v1.JobRequest
	4, // 4: worker.v1.WorkerService.GetStatus:input_type -> worker.v1.StatusRequest
	6, // 5: worker.v1.WorkerService.CancelJob:input_type -> worker.v1.CancelRequest
	3, // 6: worker.v1.WorkerService.SubmitJob:output_type -> worker.v1.JobProgress
	5, // 7: worker.v1.WorkerService.GetStatus:output_type -> worker.v1.WorkerStatus
	7, // 8: worker.v1.WorkerService.CancelJob:output_type -> worker.v1.CancelResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_worker_v1_worker_proto_init() }
func file_proto_worker_v1_worker_proto_init() {
	if File_proto_worker_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_worker_v1_worker_proto_rawDesc), len(file_proto_worker_v1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_proto_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_proto_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_proto_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_proto_worker_v1_worker_proto = out.File
	file_proto_worker_v1_worker_proto_goTypes = nil
	file_proto_worker_v1_worker_proto_depIdxs = nil
}
